Hmm ... how come?
java.lang.NoClassDefFoundError: org/apache/commons/io/FileUtils
	at de.retest.web.IntegrationTest.setup(IntegrationTest.java:39)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.FileUtils
	at de.retest.web.IntegrationTest.setup(IntegrationTest.java:39)